--DML PARA LLENAR LOS REGISTROS DE LA TABLA TAB_PRUEBA PRUEBA ------------------------------------------------------------------------------------------------------------------------------------
-- SELECT * FROM TAB_PRUEBA;



--FUNCIONES DE INSERCION LA TABLA TAB_PRUEBA ----------------------------------------------------------------------------------------------------------------------------
INSERT INTO tab_prueba VALUES(1,'PRUEBA1','DESCRIPCION PRUEBA 1');
INSERT INTO tab_prueba VALUES(2,'PRUEBA2','DESCRIPCION PRUEBA 2');
INSERT INTO tab_prueba VALUES(3,'PRUEBA3','DESCRIPCION PRUEBA 3');
INSERT INTO tab_prueba VALUES(4,'PRUEBA4','DESCRIPCION PRUEBA 4');
INSERT INTO tab_prueba VALUES(5,'PRUEBA5','DESCRIPCION PRUEBA 5');
INSERT INTO tab_prueba VALUES(6,'PRUEBA6','DESCRIPCION PRUEBA 6');
INSERT INTO tab_prueba VALUES(7,'PRUEBA7','DESCRIPCION PRUEBA 7');
INSERT INTO tab_prueba VALUES(8,'PRUEBA8','DESCRIPCION PRUEBA 8');
INSERT INTO tab_prueba VALUES(9,'PRUEBA9','DESCRIPCION PRUEBA 9');
INSERT INTO tab_prueba VALUES(10,'PRUEBA10','DESCRIPCION PRUEBA 10');