--DML PARA LA TABLA TAB_CONTEXTO------------------------------------------------------------------------------------------------------------------------------------------------
-- SELECT * FROM TAB_CONTEXTO;

--FUNCIONES DE INSERCION LA TABLA TAB_CONTEXTO------------------------------------------------------------------------------------------------------------
SELECT FUN_INSERTAR_CONTEXTO('SIN CONTEXTO','CONTEXTO PARA PREGUNTAS SIN CONTEXTO, (OBLIGATORIO)','SIN CONTEXTO','SIN CONTEXTO');
