-- DML PARA LLENAR LOS REGISTROS DE LA TABLA TAB_AREAS_EVALUAR PRUEBA
-- SELECT * FROM TAB_AREAS_EVALUAR;


-- FUNCIONES DE INSERCION LA TABLA TAB_AREAS_EVALUAR TODOS CON PONDERACION 1------------------------------------------------------------------------------------------------------------
SELECT FUN_INSERTAR_AREAS_EVALUAR('RAZONAMIENTO CUANTITATIVO TYT',' En esta area se evalua matematicas',1);
SELECT FUN_INSERTAR_AREAS_EVALUAR('LECTURA CRITICA TYT','En esta area se evalua español',1);
SELECT FUN_INSERTAR_AREAS_EVALUAR('COMPETENCIAS CIUDADANAS TYT','En esta area se evaluara competencias ciudadanas',1);
SELECT FUN_INSERTAR_AREAS_EVALUAR('INGLES TYT','En esta area se evaluara ingles',1);






